# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BashPilot < Formula
  desc "A powerful CLI toolkit for bash power users — SSH, Git, Env, Prompt"
  homepage "https://github.com/somaz94/bash-pilot"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.0/bash-pilot_0.6.0_darwin_amd64.tar.gz"
      sha256 "5c196beae9c54fc18dd78a9f9673b1845bcb63dabda71132342934f215a8d4a7"

      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.0/bash-pilot_0.6.0_darwin_arm64.tar.gz"
      sha256 "53b5bd19f1b093fd57a05e398a9c13fe22c81b0c912a63fd77a3444e1b6ea8a1"

      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.0/bash-pilot_0.6.0_linux_amd64.tar.gz"
      sha256 "a3ebf0e5cb5399043b5dc9b83b9a9095eca9a433530f63fb02053d1c38bf6a15"
      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.0/bash-pilot_0.6.0_linux_arm64.tar.gz"
      sha256 "7792a5a7d65372c38cd84b28c080808b4449a3961bdc808ede5c1280c1e956c1"
      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
  end

  def caveats
    <<~EOS
      🎉 bash-pilot installed!

      Quick start:
        bash-pilot init                  # Auto-generate config from SSH config
        bash-pilot ssh list              # List SSH hosts with grouping
        bash-pilot ssh ping              # Test connectivity (parallel)
        bash-pilot ssh audit             # Security audit
        bash-pilot git profiles          # List git identity profiles
        bash-pilot git doctor            # Diagnose gitconfig issues
        bash-pilot git clean --dry-run   # Preview stale/duplicate cleanup
        bash-pilot env check             # Shell environment health scan
        bash-pilot env path              # PATH analysis
        bash-pilot prompt init           # Generate smart bash prompt
        bash-pilot prompt show           # Preview prompt components
        bash-pilot snapshot --summary    # Environment snapshot summary
        bash-pilot diff my-env.json      # Compare environments
        bash-pilot setup my-env.json     # Install missing tools
        bash-pilot migrate export        # Export SSH + Git config
        bash-pilot migrate import f.json # Import config on new machine
        bash-pilot doctor                # Full system diagnostics
        bash-pilot --help                # Full usage

      Docs: https://github.com/somaz94/bash-pilot
    EOS
  end

  test do
    system "#{bin}/bash-pilot", "version"
  end
end
