# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BashPilot < Formula
  desc "A powerful CLI toolkit for bash power users — SSH, Git, Env, Prompt"
  homepage "https://github.com/somaz94/bash-pilot"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.1/bash-pilot_0.6.1_darwin_amd64.tar.gz"
      sha256 "034a6f241600fde9837d8650ff23645b6e755c727c5a6daab95df9e1d123da9a"

      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.1/bash-pilot_0.6.1_darwin_arm64.tar.gz"
      sha256 "0206193c7e61f57fbed21dd5cde5557fade0ccb4c0477e2b17ac1152696a50d9"

      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.1/bash-pilot_0.6.1_linux_amd64.tar.gz"
      sha256 "625d10b9c382f1b81f8156a58a7570aa923ab7dc3101fda033e5f78b4629ee55"
      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.1/bash-pilot_0.6.1_linux_arm64.tar.gz"
      sha256 "2c41da106d38092532d18b43ed6e7935b47a04c7f9f9b6036121a6996121286f"
      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
  end

  def caveats
    <<~EOS
      🎉 bash-pilot installed!

      Quick start:
        bash-pilot init                  # Auto-generate config from SSH config
        bash-pilot ssh list              # List SSH hosts with grouping
        bash-pilot ssh ping              # Test connectivity (parallel)
        bash-pilot ssh audit             # Security audit
        bash-pilot git profiles          # List git identity profiles
        bash-pilot git doctor            # Diagnose gitconfig issues
        bash-pilot git clean --dry-run   # Preview stale/duplicate cleanup
        bash-pilot env check             # Shell environment health scan
        bash-pilot env path              # PATH analysis
        bash-pilot prompt init           # Generate smart bash prompt
        bash-pilot prompt show           # Preview prompt components
        bash-pilot snapshot --summary    # Environment snapshot summary
        bash-pilot diff my-env.json      # Compare environments
        bash-pilot setup my-env.json     # Install missing tools
        bash-pilot migrate export        # Export SSH + Git config
        bash-pilot migrate import f.json # Import config on new machine
        bash-pilot doctor                # Full system diagnostics
        bash-pilot --help                # Full usage

      Docs: https://github.com/somaz94/bash-pilot
    EOS
  end

  test do
    system "#{bin}/bash-pilot", "version"
  end
end
