# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BashPilot < Formula
  desc "A powerful CLI toolkit for bash power users — SSH, Git, Env, Prompt"
  homepage "https://github.com/somaz94/bash-pilot"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.2/bash-pilot_0.6.2_darwin_amd64.tar.gz"
      sha256 "a06554ab7a43d12ce6bddd23cac8a82ddee8abf01ae522dbdfb5d23168115695"

      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.2/bash-pilot_0.6.2_darwin_arm64.tar.gz"
      sha256 "2f8fc9ac8e0680dd9e85c4a36455acb5472fae987ff90553949ed0aff92aec56"

      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.2/bash-pilot_0.6.2_linux_amd64.tar.gz"
      sha256 "2be6597bb7c730153acec0cf040b89d91e479997d5d4d617456833a4d1803ba1"
      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/bash-pilot/releases/download/v0.6.2/bash-pilot_0.6.2_linux_arm64.tar.gz"
      sha256 "b641be0a420f98bf992ace3856bd2a16b45bece1db186ecf636d128207632c00"
      define_method(:install) do
        bin.install "bash-pilot"
      end
    end
  end

  def caveats
    <<~EOS
      🎉 bash-pilot installed!

      Quick start:
        bash-pilot init                  # Auto-generate config from SSH config
        bash-pilot ssh list              # List SSH hosts with grouping
        bash-pilot ssh ping              # Test connectivity (parallel)
        bash-pilot ssh audit             # Security audit
        bash-pilot git profiles          # List git identity profiles
        bash-pilot git doctor            # Diagnose gitconfig issues
        bash-pilot git clean --dry-run   # Preview stale/duplicate cleanup
        bash-pilot env check             # Shell environment health scan
        bash-pilot env path              # PATH analysis
        bash-pilot prompt init           # Generate smart bash prompt
        bash-pilot prompt show           # Preview prompt components
        bash-pilot snapshot --summary    # Environment snapshot summary
        bash-pilot diff my-env.json      # Compare environments
        bash-pilot setup my-env.json     # Install missing tools
        bash-pilot migrate export        # Export SSH + Git config
        bash-pilot migrate import f.json # Import config on new machine
        bash-pilot doctor                # Full system diagnostics
        bash-pilot --help                # Full usage

      Docs: https://github.com/somaz94/bash-pilot
    EOS
  end

  test do
    system "#{bin}/bash-pilot", "version"
  end
end
