# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeDiff < Formula
  desc "Compare local Kubernetes manifests against live cluster state"
  homepage "https://github.com/somaz94/kube-diff"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.4.1/kube-diff_0.4.1_darwin_amd64.tar.gz"
      sha256 "2d7e2b6e7af5b45c9abc5a1c8ba5e4b1f6ad1d1812e7bb13b540be5797eb6706"

      define_method(:install) do
        bin.install "kube-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.4.1/kube-diff_0.4.1_darwin_arm64.tar.gz"
      sha256 "44ebc90a59accbefbed7b5db04563df13ed64d69779893e4b4f00ee7595b7113"

      define_method(:install) do
        bin.install "kube-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.4.1/kube-diff_0.4.1_linux_amd64.tar.gz"
      sha256 "a1c4aa2a979a81bbe5529109cb453dbdc64e5ba2820519efae3b5b81373af4b7"
      define_method(:install) do
        bin.install "kube-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.4.1/kube-diff_0.4.1_linux_arm64.tar.gz"
      sha256 "1313d17b70e0919cb3de583be1e25cc6f34d92b55197f4c97589133b89222412"
      define_method(:install) do
        bin.install "kube-diff"
      end
    end
  end

  def caveats
    <<~EOS
      🎉 kube-diff installed!

      Quick start:
        kube-diff file <path>              # Compare YAML files vs cluster
        kube-diff helm <chart> -r <name>   # Compare Helm chart vs cluster
        kube-diff kustomize <path>         # Compare Kustomize vs cluster
        kube-diff --help                   # Full usage

      Docs: https://github.com/somaz94/kube-diff
    EOS
  end

  test do
    system "#{bin}/kube-diff", "version"
  end
end
