# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeDiff < Formula
  desc "Compare local Kubernetes manifests against live cluster state"
  homepage "https://github.com/somaz94/kube-diff"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.4.0/kube-diff_0.4.0_darwin_amd64.tar.gz"
      sha256 "675b57223e86257b25a4ae18fe8157418f2923327f138dad1cc2bbe315a8dbb1"

      define_method(:install) do
        bin.install "kube-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.4.0/kube-diff_0.4.0_darwin_arm64.tar.gz"
      sha256 "9973922e7fd45e6741212fc46f331dc628825f71f4c6450badcb26091c900208"

      define_method(:install) do
        bin.install "kube-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.4.0/kube-diff_0.4.0_linux_amd64.tar.gz"
      sha256 "021a83aec955ff1dc51aa743925bf61b241fed77b190c24de5d759670719b1db"
      define_method(:install) do
        bin.install "kube-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.4.0/kube-diff_0.4.0_linux_arm64.tar.gz"
      sha256 "24ae96f8016ab179570bd6ad3bb5c92e980a35bbe0fbef6896a054b6496c7e27"
      define_method(:install) do
        bin.install "kube-diff"
      end
    end
  end

  test do
    system "#{bin}/kube-diff", "version"
  end
end
