# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeCtx < Formula
  desc "Switch Kubernetes contexts and namespaces, per-terminal and with production guards"
  homepage "https://github.com/somaz94/kube-ctx"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/kube-ctx/releases/download/v0.2.0/kube-ctx_0.2.0_darwin_amd64.tar.gz"
      sha256 "4a4061d7d5d6de38795e6761b67a8342cbf615d019fa60121fb540a6a35fe3b4"

      define_method(:install) do
        bin.install "kctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/kube-ctx/releases/download/v0.2.0/kube-ctx_0.2.0_darwin_arm64.tar.gz"
      sha256 "7a6a92b9a5d621e9a56c41a5896a0edf6beadc740712e9181cf252b4eefcd69f"

      define_method(:install) do
        bin.install "kctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-ctx/releases/download/v0.2.0/kube-ctx_0.2.0_linux_amd64.tar.gz"
      sha256 "38deb9d06f59d8ec71095bd76643d75508c5017556834708559bfe41ec62dfc8"
      define_method(:install) do
        bin.install "kctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-ctx/releases/download/v0.2.0/kube-ctx_0.2.0_linux_arm64.tar.gz"
      sha256 "443757ed20a7f10b3fbaab77af07abb2eeb55a723cf0be3661a56d6a804b5f9d"
      define_method(:install) do
        bin.install "kctx"
      end
    end
  end

  def caveats
    <<~EOS
      🎉 kctx installed!

      Quick start:
        kctx                       # Interactive context picker
        kctx ctx prod-eks          # Switch context
        kctx ns kube-system        # Switch namespace
        kctx doctor                # Check every cluster
        kctx --help                # Full usage

      For per-terminal context isolation, add to your rc file:
        eval "$(kctx init zsh)"    # bash: kctx init bash
                                   # fish: kctx init fish | source

      Docs: https://github.com/somaz94/kube-ctx
    EOS
  end

  test do
    system "#{bin}/kctx", "version"
  end
end
