# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeEvents < Formula
  desc "View and summarize Kubernetes events with grouping and highlighting"
  homepage "https://github.com/somaz94/kube-events"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/kube-events/releases/download/v0.3.0/kube-events_0.3.0_darwin_amd64.tar.gz"
      sha256 "4ac4d8f50d24b01f8b1d97754ff456127b27403c212b90bdbf17d64f23547b9d"

      define_method(:install) do
        bin.install "kube-events"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/kube-events/releases/download/v0.3.0/kube-events_0.3.0_darwin_arm64.tar.gz"
      sha256 "9525d66f4c74770bbe82b1c80b52c4280a70b77956bceba02f3062c140c8b6ec"

      define_method(:install) do
        bin.install "kube-events"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-events/releases/download/v0.3.0/kube-events_0.3.0_linux_amd64.tar.gz"
      sha256 "d60bab5d944e8aa08ed6533bb395e776f0c10862fce1deb311fc1395adf90d64"
      define_method(:install) do
        bin.install "kube-events"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-events/releases/download/v0.3.0/kube-events_0.3.0_linux_arm64.tar.gz"
      sha256 "b5aa56f267766ccd59b209facbc95811a0e7d8def14a34605d05666fc402a4f3"
      define_method(:install) do
        bin.install "kube-events"
      end
    end
  end

  def caveats
    <<~EOS
      🎉 kube-events installed!

      Quick start:
        kube-events                        # View recent events (last 1h)
        kube-events -n <namespace>         # Filter by namespace
        kube-events -t Warning             # Show warnings only
        kube-events -g namespace           # Group by namespace
        kube-events -w                     # Watch events in real-time
        kube-events -s                     # Summary statistics only
        kube-events --help                 # Full usage

      Docs: https://github.com/somaz94/kube-events
    EOS
  end

  test do
    system "#{bin}/kube-events", "version"
  end
end
