# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeEvents < Formula
  desc "View and summarize Kubernetes events with grouping and highlighting"
  homepage "https://github.com/somaz94/kube-events"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/kube-events/releases/download/v0.1.0/kube-events_0.1.0_darwin_amd64.tar.gz"
      sha256 "717386e553c09483a1ebe2b002246ce0a9fc7e520c498f97bfa4a99c827f7f06"

      define_method(:install) do
        bin.install "kube-events"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/kube-events/releases/download/v0.1.0/kube-events_0.1.0_darwin_arm64.tar.gz"
      sha256 "e12e3180d708631bd5931b5dd99133d76926625626ed6209b3484cb1f90a059a"

      define_method(:install) do
        bin.install "kube-events"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-events/releases/download/v0.1.0/kube-events_0.1.0_linux_amd64.tar.gz"
      sha256 "f3f1c9539c93081e31b2592f2e28d61428afe676a14128d8a7956be4c7505086"
      define_method(:install) do
        bin.install "kube-events"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-events/releases/download/v0.1.0/kube-events_0.1.0_linux_arm64.tar.gz"
      sha256 "6360b854d255a9d6b04e24c3d9683cf08912b618c145b91d0b956ad7e84be68b"
      define_method(:install) do
        bin.install "kube-events"
      end
    end
  end

  test do
    system "#{bin}/kube-events", "version"
  end
end
