# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeDiff < Formula
  desc "Compare local Kubernetes manifests against live cluster state"
  homepage "https://github.com/somaz94/kube-diff"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.5.0/kube-diff_0.5.0_darwin_amd64.tar.gz"
      sha256 "61f14da4ebe0454a216d991a6d854a88eb5f49e4203746a82a39ea9260f2ec87"

      define_method(:install) do
        bin.install "kube-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.5.0/kube-diff_0.5.0_darwin_arm64.tar.gz"
      sha256 "86133eead9ea73f64d83b6f47c62ba545df2807eb40179058d0f7e77b3bd9656"

      define_method(:install) do
        bin.install "kube-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.5.0/kube-diff_0.5.0_linux_amd64.tar.gz"
      sha256 "6f0848a8e32cbef06ab50587894a36951dd5c3698a6d7087779033208d6585dd"
      define_method(:install) do
        bin.install "kube-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-diff/releases/download/v0.5.0/kube-diff_0.5.0_linux_arm64.tar.gz"
      sha256 "634276cef1084c6a9308b02499a1517b09c712b11adae64ec51d7b7ec9ca7135"
      define_method(:install) do
        bin.install "kube-diff"
      end
    end
  end

  def caveats
    <<~EOS
      🎉 kube-diff installed!

      Quick start:
        kube-diff file <path>              # Compare YAML files vs cluster
        kube-diff helm <chart> -r <name>   # Compare Helm chart vs cluster
        kube-diff kustomize <path>         # Compare Kustomize vs cluster
        kube-diff --help                   # Full usage

      Docs: https://github.com/somaz94/kube-diff
    EOS
  end

  test do
    system "#{bin}/kube-diff", "version"
  end
end
