# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeCtx < Formula
  desc "Switch Kubernetes contexts and namespaces, per-terminal and with production guards"
  homepage "https://github.com/somaz94/kube-ctx"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/somaz94/kube-ctx/releases/download/v0.1.0/kube-ctx_0.1.0_darwin_amd64.tar.gz"
      sha256 "4b2b05c78654117cc720ac432b6f6702a69fcbad5b51d0e264af7ba27ccd3c70"

      define_method(:install) do
        bin.install "kctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/somaz94/kube-ctx/releases/download/v0.1.0/kube-ctx_0.1.0_darwin_arm64.tar.gz"
      sha256 "294351d43eb3d5978e65d3930008e1dca1daa9899a6ff66ec143331bf34452ae"

      define_method(:install) do
        bin.install "kctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-ctx/releases/download/v0.1.0/kube-ctx_0.1.0_linux_amd64.tar.gz"
      sha256 "c87daa1c2c6a9936897d66c0228832d3105fd818ec18e340f2c2026ec5c63def"
      define_method(:install) do
        bin.install "kctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/somaz94/kube-ctx/releases/download/v0.1.0/kube-ctx_0.1.0_linux_arm64.tar.gz"
      sha256 "9300e0c8d28a8fcee1ee28c63611fda31a882b054b2d41cd9a36ac94de49c377"
      define_method(:install) do
        bin.install "kctx"
      end
    end
  end

  def caveats
    <<~EOS
      🎉 kctx installed!

      Quick start:
        kctx                       # Interactive context picker
        kctx ctx prod-eks          # Switch context
        kctx ns kube-system        # Switch namespace
        kctx doctor                # Check every cluster
        kctx --help                # Full usage

      For per-terminal context isolation, add to your rc file:
        eval "$(kctx init zsh)"    # bash: kctx init bash
                                   # fish: kctx init fish | source

      Docs: https://github.com/somaz94/kube-ctx
    EOS
  end

  test do
    system "#{bin}/kctx", "version"
  end
end
