# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentport" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "bd6da1c780405f3db4fe0f2bbffbdad99ffc4626a100815d8f63ba3764b2f41c"
      url "https://github.com/somaz94/agentport/releases/download/v#{version}/agentport_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b31faee03623cca97ae5fc9695ae9ed41f251b03272906c611dab076ddce90e4"
      url "https://github.com/somaz94/agentport/releases/download/v#{version}/agentport_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f296cffb463b39800dc7ae827f03b5e181ae728f26e69a8a3b8f3a61ba8ebbf6"
      url "https://github.com/somaz94/agentport/releases/download/v#{version}/agentport_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "308374c943b3915898f5457301c4ecd22f4093f62da7436c91994c5b9e0c2daf"
      url "https://github.com/somaz94/agentport/releases/download/v#{version}/agentport_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentport"
  desc "Convert Claude Code skills, commands and subagents to Codex and Antigravity formats"
  homepage "https://github.com/somaz94/agentport"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentport"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentport"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    agentport installed!

    Quick start:
      agentport scan          # What each harness has installed, and how portable it is
      agentport sync          # Preview converting ~/.claude into every target
      agentport --help        # Full usage

    Docs: https://github.com/somaz94/agentport
  EOS
end
