# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentport" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "38ed0f429f1b847b4b51dc68bd2b70bef0ad8df8a829834a50d5f328503748fe"
      url "https://github.com/somaz94/agentport/releases/download/v#{version}/agentport_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "89a7ef3f674b2f6e60914e6f04e9d2518ddb2321e0e87451e15f9ffcd023c7e5"
      url "https://github.com/somaz94/agentport/releases/download/v#{version}/agentport_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a2408730cb8ee89cbfaa188c3e3fcb3ca5c1fce952216f43a782e3447440f04d"
      url "https://github.com/somaz94/agentport/releases/download/v#{version}/agentport_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7a692b6252c450a1142cf46b8c38e4e1e67e3a7f323b26e21fd7396be5e1fa5"
      url "https://github.com/somaz94/agentport/releases/download/v#{version}/agentport_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentport"
  desc "Convert Claude Code skills, commands and subagents to Codex and Antigravity formats"
  homepage "https://github.com/somaz94/agentport"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentport"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentport"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    agentport installed!

    Quick start:
      agentport scan          # What each harness has installed, and how portable it is
      agentport sync          # Preview converting ~/.claude into every target
      agentport --help        # Full usage

    Docs: https://github.com/somaz94/agentport
  EOS
end
