# This file was generated by GoReleaser. DO NOT EDIT.
cask "bash-pilot" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "870a44915ff4d99a0393cbf641fce61f7b3ae7d047968c0125fce43103a452f9"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0713f71a520e30dacdf7ccd46470bb098cd81a780c6a0a5a322eba9de38fbfa1"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ff8fc5d116e686205354c000f2a2dcff5dbe2add9db36d93350c99d3fd16b27e"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8788fefeb8e1e85622b812ffffd21ffc5aeb1a7fc974f5fa7e74d951af0cb3a3"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bash-pilot"
  desc "A powerful CLI toolkit for bash power users — SSH, Git, Env, Prompt"
  homepage "https://github.com/somaz94/bash-pilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bash-pilot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bash-pilot"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 bash-pilot installed!

    Quick start:
      bash-pilot init                  # Auto-generate config from SSH config
      bash-pilot ssh list              # List SSH hosts with grouping
      bash-pilot ssh ping              # Test connectivity (parallel)
      bash-pilot ssh audit             # Security audit
      bash-pilot git profiles          # List git identity profiles
      bash-pilot git doctor            # Diagnose gitconfig issues
      bash-pilot git clean --dry-run   # Preview stale/duplicate cleanup
      bash-pilot env check             # Shell environment health scan
      bash-pilot env path              # PATH analysis
      bash-pilot prompt init           # Generate smart bash prompt
      bash-pilot prompt show           # Preview prompt components
      bash-pilot snapshot --summary    # Environment snapshot summary
      bash-pilot diff my-env.json      # Compare environments
      bash-pilot setup my-env.json     # Install missing tools
      bash-pilot migrate export        # Export SSH + Git config
      bash-pilot migrate import f.json # Import config on new machine
      bash-pilot doctor                # Full system diagnostics
      bash-pilot --help                # Full usage

    Docs: https://github.com/somaz94/bash-pilot
  EOS
end
