# This file was generated by GoReleaser. DO NOT EDIT.
cask "bash-pilot" do
  version "0.6.3"

  on_macos do
    on_intel do
      sha256 "d9bf95c4c2450cac1a465f4dd946cdc820c76ef0064cb2f28ff5f034742a4809"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "212d641d2ef635f80467fedf431d8b88abe657e2e5c1a64d1ba0cac20f7bf196"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bf9e56615235e35a7b8b1ac190c1590556fe1450bb90c3318df0ec47be594d6a"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "14bdb16595a02fe1022131baab0a19ff0c962188afd9b583b18b8e9875b45a34"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bash-pilot"
  desc "A powerful CLI toolkit for bash power users — SSH, Git, Env, Prompt"
  homepage "https://github.com/somaz94/bash-pilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bash-pilot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bash-pilot"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 bash-pilot installed!

    Quick start:
      bash-pilot init                  # Auto-generate config from SSH config
      bash-pilot ssh list              # List SSH hosts with grouping
      bash-pilot ssh ping              # Test connectivity (parallel)
      bash-pilot ssh audit             # Security audit
      bash-pilot git profiles          # List git identity profiles
      bash-pilot git doctor            # Diagnose gitconfig issues
      bash-pilot git clean --dry-run   # Preview stale/duplicate cleanup
      bash-pilot env check             # Shell environment health scan
      bash-pilot env path              # PATH analysis
      bash-pilot prompt init           # Generate smart bash prompt
      bash-pilot prompt show           # Preview prompt components
      bash-pilot snapshot --summary    # Environment snapshot summary
      bash-pilot diff my-env.json      # Compare environments
      bash-pilot setup my-env.json     # Install missing tools
      bash-pilot migrate export        # Export SSH + Git config
      bash-pilot migrate import f.json # Import config on new machine
      bash-pilot doctor                # Full system diagnostics
      bash-pilot --help                # Full usage

    Docs: https://github.com/somaz94/bash-pilot
  EOS
end
