# This file was generated by GoReleaser. DO NOT EDIT.
cask "bash-pilot" do
  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "a80085c839fbf3bcc3823e53a7ff863830b9ba6fbbc9c3c116192bf8551ba8fd"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "04651f82f2905096cecdf3d7258ec2a5bc5b7a89d5e4bb84ffca5335b8cf84d3"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "79288dca2fbe1975f568d6ddb30bb8723565f465fe2d6b212bc0c731590b1c01"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4cf4ff8135d063ebd42c6d968a8c9ba3ef9b9afd995c72435681d427e0e15754"
      url "https://github.com/somaz94/bash-pilot/releases/download/v#{version}/bash-pilot_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bash-pilot"
  desc "A powerful CLI toolkit for bash power users — SSH, Git, Env, Prompt"
  homepage "https://github.com/somaz94/bash-pilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bash-pilot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bash-pilot"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 bash-pilot installed!

    Quick start:
      bash-pilot init                  # Auto-generate config from SSH config
      bash-pilot ssh list              # List SSH hosts with grouping
      bash-pilot ssh ping              # Test connectivity (parallel)
      bash-pilot ssh audit             # Security audit
      bash-pilot git profiles          # List git identity profiles
      bash-pilot git doctor            # Diagnose gitconfig issues
      bash-pilot git clean --dry-run   # Preview stale/duplicate cleanup
      bash-pilot env check             # Shell environment health scan
      bash-pilot env path              # PATH analysis
      bash-pilot prompt init           # Generate smart bash prompt
      bash-pilot prompt show           # Preview prompt components
      bash-pilot snapshot --summary    # Environment snapshot summary
      bash-pilot diff my-env.json      # Compare environments
      bash-pilot setup my-env.json     # Install missing tools
      bash-pilot migrate export        # Export SSH + Git config
      bash-pilot migrate import f.json # Import config on new machine
      bash-pilot doctor                # Full system diagnostics
      bash-pilot --help                # Full usage

    Docs: https://github.com/somaz94/bash-pilot
  EOS
end
