# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-chart-kit" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "23cbfbdb066bc248ce81f80a9ad6d25c96fb3061287371cc32ee3f8a425c0a93"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "247a3e034d911abc6f5972aaec7d1768f6463edde8cabc907dc6aaa2797078b8"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f9bf31e667b9c9883d9bbf4f4a2e5dba8c0ae24915a4a799ccf7109de5907290"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "301cda41046a4b2ca4ec1afacf9362ca8651ec242f66c51f85fe55c6578ae830"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "helm-chart-kit"
  desc "Scaffold Helm charts and add resources to existing ones"
  homepage "https://github.com/somaz94/helm-chart-kit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hck"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    hck installed!

    Quick start:
      hck new my-app             # Scaffold a chart from the web preset
      hck add servicemonitor     # Add a resource to an existing chart
      hck check                  # Render it and apply the house rules
      hck list                   # Every preset and resource
      hck --help                 # Full usage

    hck check shells out to helm, so install helm for that subcommand.

    Docs: https://github.com/somaz94/helm-chart-kit
  EOS
end
