# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-chart-kit" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7da9f82f1b995559b3f9a65eec2b924f5cad5a89c17fd3c6b57ef0707476a561"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b0b3e4ccb898baed67aa844c9ff118207fc8f8b7fb348f64de6cbb4d1dce4f3b"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0027a362f37f837f41bdd7a702e290760a1e91757db0670da9f69bb044f9ba8d"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac0fbdbc74290b6d07a95f372adafee3f4f0bb696784615004f71dc0a1efcd6d"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "helm-chart-kit"
  desc "Scaffold Helm charts and add resources to existing ones"
  homepage "https://github.com/somaz94/helm-chart-kit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hck"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    hck installed!

    Quick start:
      hck new my-app             # Scaffold a chart from the web preset
      hck add servicemonitor     # Add a resource to an existing chart
      hck check                  # Render it and apply the house rules
      hck list                   # Every preset and resource
      hck --help                 # Full usage

    hck check shells out to helm, so install helm for that subcommand.

    Docs: https://github.com/somaz94/helm-chart-kit
  EOS
end
