# This file was generated by GoReleaser. DO NOT EDIT.
cask "helm-chart-kit" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "cca123ab0e4454433f128b9f04c52ade9dc9aadd3d11b83442c21a4bb391a655"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "328855b49a452cae8d24f990453159a9bcaf28d5608bc18c86227112da0a50de"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "810e13d1fc8ed4e702c0d0994b399e3848cb6e075bf676312ada4e03e02420e9"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1205d2adb041fed78ce13b8f555ba620ba0609c4e875bfc21636b0b653c20475"
      url "https://github.com/somaz94/helm-chart-kit/releases/download/v#{version}/helm-chart-kit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "helm-chart-kit"
  desc "Scaffold Helm charts and add resources to existing ones"
  homepage "https://github.com/somaz94/helm-chart-kit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hck"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    hck installed!

    Quick start:
      hck new my-app             # Scaffold a chart from the web preset
      hck add servicemonitor     # Add a resource to an existing chart
      hck check                  # Render it and apply the house rules
      hck list                   # Every preset and resource
      hck --help                 # Full usage

    hck check shells out to helm, so install helm for that subcommand.

    Docs: https://github.com/somaz94/helm-chart-kit
  EOS
end
