# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-ctx" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "d0007c1d61607379f72990a296927ae92353f91d66143fd646e0992f14c9f8fd"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "abef60c877f4423b60d30f6337141ce1027d6eebec08b1bff528cb17a034fbd9"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d0378eac7f9f70f86c7e90acf8f9ac346310953d045eab2580d05428084ea15"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7543f7216b2f05c2f7c26bb13ef995cb2a89d823d83e2b25fb1d2dc532c941cb"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kube-ctx"
  desc "Switch Kubernetes contexts and namespaces, per-terminal and with production guards"
  homepage "https://github.com/somaz94/kube-ctx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kctx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kctx"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 kctx installed!

    Quick start:
      kctx                       # Interactive context picker
      kctx ctx prod-eks          # Switch context
      kctx ns kube-system        # Switch namespace
      kctx doctor                # Check every cluster
      kctx --help                # Full usage

    For per-terminal context isolation, add to your rc file:
      eval "$(kctx init zsh)"    # bash: kctx init bash
                                 # fish: kctx init fish | source

    Docs: https://github.com/somaz94/kube-ctx
  EOS
end
