# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-diff" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "56c3d1096b8d0dfb091d30df3b989d405d74b1c0acdf7ff3cec73fef1cb1d3e6"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a47ad8fce3028f6b341ffbf65e4eda5c001b3cdc68600f93c8ef16a9ff2c58ab"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "75c9b05804eea35e643f4e69a1c1de88db882f25dc0d05c0febca020f29c1484"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a69df2a4ae774ac8bc231442d87c9ec9743a502a60a5e90d6a65027a59d6787a"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kube-diff"
  desc "Compare local Kubernetes manifests against live cluster state"
  homepage "https://github.com/somaz94/kube-diff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-diff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kube-diff"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 kube-diff installed!

    Quick start:
      kube-diff file <path>              # Compare YAML files vs cluster
      kube-diff helm <chart> -r <name>   # Compare Helm chart vs cluster
      kube-diff kustomize <path>         # Compare Kustomize vs cluster
      kube-diff --help                   # Full usage

    Docs: https://github.com/somaz94/kube-diff
  EOS
end
