# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-diff" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "f94c0e6efc7221042b7d685784de0b2ee4143834988d48dbe5ddfa9e4a9af39b"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a74aac286c417fc72efef1b5ab556f9e91edbe706b108890e9c9180462c56cb"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "583956d3e3b38b6a254c80b27caef67e751e3fa399e4adfde45ae7a4c19da83e"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "18204f6f2606c22e54fbe9fcc5765b0f23242d065e3a4761587e348d50ff7ad8"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kube-diff"
  desc "Compare local Kubernetes manifests against live cluster state"
  homepage "https://github.com/somaz94/kube-diff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-diff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kube-diff"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 kube-diff installed!

    Quick start:
      kube-diff file <path>              # Compare YAML files vs cluster
      kube-diff helm <chart> -r <name>   # Compare Helm chart vs cluster
      kube-diff kustomize <path>         # Compare Kustomize vs cluster
      kube-diff --help                   # Full usage

    Docs: https://github.com/somaz94/kube-diff
  EOS
end
