# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-diff" do
  version "0.5.3"

  on_macos do
    on_arm do
      sha256 "42e9c8f872e7d2612b79c0f42acb927fd9cf2af232d89130791eaa2b4b6244fa"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d89e0397ed21359057692fc88ac8e0b7c0e56569d04464dba03e4a23b638d70c"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6008d6d538a5b9f3be3049a28d641f8c047bee5567ed9fac4c5d2908e4858eaf"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b41dd93d23746bff6a4c133a51df0427712896b7a68b23830051312585398221"
      url "https://github.com/somaz94/kube-diff/releases/download/v#{version}/kube-diff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kube-diff"
  desc "Compare local Kubernetes manifests against live cluster state"
  homepage "https://github.com/somaz94/kube-diff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-diff"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kube-diff"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 kube-diff installed!

    Quick start:
      kube-diff file <path>              # Compare YAML files vs cluster
      kube-diff helm <chart> -r <name>   # Compare Helm chart vs cluster
      kube-diff kustomize <path>         # Compare Kustomize vs cluster
      kube-diff --help                   # Full usage

    Docs: https://github.com/somaz94/kube-diff
  EOS
end
