# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-events" do
  version "0.3.5"

  on_macos do
    on_arm do
      sha256 "632b7a6b19414953cc6819bb47ef84f80b41436d4953154c4bd7eee8b4444308"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a35a39da4f6d6d91655e30608155c05e3c35e91e3526c52b463749217a015ccb"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "975991e43a8effdf3eaf45dbe57e931d005d518155bfe737badc82706b979af7"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3657c4d0184c45668afb937b00922fe8c0de41f73e94906195f69648cb5c914e"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kube-events"
  desc "View and summarize Kubernetes events with grouping and highlighting"
  homepage "https://github.com/somaz94/kube-events"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-events"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kube-events"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 kube-events installed!

    Quick start:
      kube-events                        # View recent events (last 1h)
      kube-events -n <namespace>         # Filter by namespace
      kube-events -t Warning             # Show warnings only
      kube-events -g namespace           # Group by namespace
      kube-events -w                     # Watch events in real-time
      kube-events -s                     # Summary statistics only
      kube-events --help                 # Full usage

    Docs: https://github.com/somaz94/kube-events
  EOS
end
