# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-ctx" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "a3fad1c0c4ef1b4042b2f36afd6a9eeca08682f422d4bd8dd87ea2e75f8c53c4"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "809f70ed536435baae018ef9fb91322d35203d2d439ceec77e92cedd92fe9e03"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "47024e28122568bb6e1f55c50ef7f10bb1ddd9d9ebf00c535d0572319198f915"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef30c4145586671691f659bb30c61b29197de4d8d06fd90252f4a0504449a2db"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kube-ctx"
  desc "Switch Kubernetes contexts and namespaces, per-terminal and with production guards"
  homepage "https://github.com/somaz94/kube-ctx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kctx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kctx"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 kctx installed!

    Quick start:
      kctx                       # Interactive context picker
      kctx ctx prod-eks          # Switch context
      kctx ns kube-system        # Switch namespace
      kctx doctor                # Check every cluster
      kctx --help                # Full usage

    For per-terminal context isolation, add to your rc file:
      eval "$(kctx init zsh)"    # bash: kctx init bash
                                 # fish: kctx init fish | source

    Docs: https://github.com/somaz94/kube-ctx
  EOS
end
