# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-ctx" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "cd6d70b28147148290b1682f7d3a059bf08329311677379d673e51c76dd6f594"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "45a8cc327310300a53593e3882bfb732c3c29d1674d9afc374b5d0a58f0d296d"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "07809fc1710d3048b99d36e3d61cade6717dbc77ccc441987f51326f650645cd"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "db10fb431b5351703e47af511dd2ba7b571e90eab07c28a7cb1ed5029947fa5d"
      url "https://github.com/somaz94/kube-ctx/releases/download/v#{version}/kube-ctx_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kube-ctx"
  desc "Switch Kubernetes contexts and namespaces, per-terminal and with production guards"
  homepage "https://github.com/somaz94/kube-ctx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kctx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kctx"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 kctx installed!

    Quick start:
      kctx                       # Interactive context picker
      kctx ctx prod-eks          # Switch context
      kctx ns kube-system        # Switch namespace
      kctx doctor                # Check every cluster
      kctx --help                # Full usage

    For per-terminal context isolation, add to your rc file:
      eval "$(kctx init zsh)"    # bash: kctx init bash
                                 # fish: kctx init fish | source

    Docs: https://github.com/somaz94/kube-ctx
  EOS
end
