# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-events" do
  version "0.3.4"

  on_macos do
    on_arm do
      sha256 "a1f6ba4630c3d05f04d3080b01c5ee96c2eda03fec18a6926550f5ea874d086b"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b0dbf76c4cbe9cc8106de753d3e72672e9484c7a425232995e6926aadd476fb"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "337a180484459a53c32f715dd46e58c2567c38e865018ccd6d80693f9cf38fe1"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b70970e1985c13b1689b537adb1a9ebd2182cf93049d7766888d81032b9c0e66"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kube-events"
  desc "View and summarize Kubernetes events with grouping and highlighting"
  homepage "https://github.com/somaz94/kube-events"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-events"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kube-events"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 kube-events installed!

    Quick start:
      kube-events                        # View recent events (last 1h)
      kube-events -n <namespace>         # Filter by namespace
      kube-events -t Warning             # Show warnings only
      kube-events -g namespace           # Group by namespace
      kube-events -w                     # Watch events in real-time
      kube-events -s                     # Summary statistics only
      kube-events --help                 # Full usage

    Docs: https://github.com/somaz94/kube-events
  EOS
end
