# This file was generated by GoReleaser. DO NOT EDIT.
cask "kube-events" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "b5c79aad1c6375633009cc3132b77b13bbf1ea14997501fdc75570d73aa08893"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c0eb5cb4ecf04ca6f8929173478e007f6a64f39118cc64d2638f5cf6e3aa557"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8212d024b677cb4ae5213f7569b879abc2b924881259d985cf48d5ca5730b5ba"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0685b90a7483a618404ea6e42d7db506af4b380b6d7d371414f7e19ca34b025d"
      url "https://github.com/somaz94/kube-events/releases/download/v#{version}/kube-events_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kube-events"
  desc "View and summarize Kubernetes events with grouping and highlighting"
  homepage "https://github.com/somaz94/kube-events"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kube-events"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kube-events"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    🎉 kube-events installed!

    Quick start:
      kube-events                        # View recent events (last 1h)
      kube-events -n <namespace>         # Filter by namespace
      kube-events -t Warning             # Show warnings only
      kube-events -g namespace           # Group by namespace
      kube-events -w                     # Watch events in real-time
      kube-events -s                     # Summary statistics only
      kube-events --help                 # Full usage

    Docs: https://github.com/somaz94/kube-events
  EOS
end
